### ISSUE TITLE
cannot import name 'parse_rule' from 'werkzeug.routing'

### ISSUE THREAD

**Issue by awesome33rabbit** [python-restx/flask-restx#481] opened 2022-10-21 04:18 UTC
<img width="237" alt="image" src="https://user-images.githubusercontent.com/43595445/197110492-096ad5c3-fd5c-4616-86d8-64f3763c3b2f.png">

python 3.9
flask 2.2.2
flask-restx 0.5.1

QuickStart CODE cannot run.

ImportError: cannot import name 'parse_rule' from 'werkzeug.routing'

**Comment by bgyori** [comment] 2022-10-22 23:13
This is a duplicate of https://github.com/python-restx/flask-restx/issues/460

**Closed** 2022-10-27 13:30 UTC
Labels: question
