### ISSUE TITLE
root page become 404 not found

### ISSUE THREAD

**Issue by fly50789** [python-restx/flask-restx#526] opened 2023-03-03 09:11 UTC
I cant see root(eq.'/') page of blueprint unless I remove Api.
But no matter what I can see '/other' page
Is any suggestion?

```
server_bp = Blueprint('server_bp', __name__,
                       template_folder='templates',
                       static_folder='static',
                       static_url_path='static',
                       )

api = Api(server_bp , version=g.__version__,
              title='CPE SERVER API',
              description='A CPE SERVER API',
              doc='/api/v1/doc/',
              )

@server_bp.route('/')
def index():
    return "root page"

@server_bp.route('/other')
def index2():
    return "other page"

```

**Comment by peter-doggart** [comment] 2023-03-03 09:32
@fly50789 This is a dupe of #523 

Due to how `flask-restx` builds paths inside `api`, if root (`/`) is not already registered when you create your API, it creates it either to serve the doc or simply returns a 404 if you specify the doc path as in your example. Unfortunately, there is no easy fix to change the `flask-restx` internal behaviour because of the flexibility flask gives users in registering endpoints. 

To fix, simply define the `/` route before you create your API object (move it above API in your code above) and it should work as expected. 

It's on my to-do list to update the docs to make this clearer!

**Comment by fly50789** [comment] 2023-03-04 17:12
Thanks for your help~

**Closed** 2023-03-04 17:12 UTC
Labels: question
